name: Test battery

on:
  pull_request:
    branches:

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run typecheck
        run: bun check

      - name: Run lint
        run: bun lint

      - name: Run tests
        run: bun test

  test-battery:
    needs:
      - typecheck
      - lint
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: Test battery passed
        run: echo "Typecheck, lint and tests succeeded."